### ISSUE TITLE
Add a transition page for the borrowers. Borrowers are directed to the transition page after they click on "Enter as a borrower" on the landing page.

### ISSUE THREAD

**Issue by karensheng** [JurisFund/JurisFund-monorepo#17]
**_The transition page should also be linked to the "Apply for funding" tab on the landing page._**

Body text:

Are you an FTX creditor and urgently need liquidity while waiting to recover your deposits from the FTX bankruptcy claims? 

Did you run into a car accident and are going through financial hardships while awaiting the settlement check from the insurance company of the counterparty?

Are you ready to get your life back on track? 
 
Get a non-recourse loan backed by your pre-settlement claims. 

No risk; if you lose your case, you don't pay us back. 

**Terms:** 

Advances are typically 10–15% of the settlement value. 

The annual interest rate (APR) is in the range of 20-30%. 

No repayment of the principal or interest is due until a settlement has been awarded. 

Interest compounds monthly. 

**CTA:**

**Get Started** 

UX: The email auth login (AA solution) will pop up when a user clicks the CTA.

**Comment by Markkos89** [comment]
I will start with this one
