### ISSUE TITLE
Lending pool overview page + onboarding for investors

### ISSUE THREAD

**Issue by karensheng** [JurisFund/JurisFund-monorepo#19]
![Image](https://github.com/JurisFund/JurisFund-monorepo/assets/46656667/14415914-eaca-4383-8889-15b4349f21e7)

Users will see a pop-up of Connect Wallet when they click on "Deposit USDC" or "Connect Wallet".

**Comment by Markkos89** [comment]
closed on https://github.com/JurisFund/JurisFund-monorepo/pull/53
