### ISSUE TITLE
Landing page for the lending pool investors

### ISSUE THREAD

**Issue by karensheng** [JurisFund/JurisFund-monorepo#46]
Use the original landing page that shows the value prop for investors. Remove the "Start as a borrower" CTA. 
Keep the "Enter investor portal" CTA. After a user clicks on this CTA, he will be directed to the lending pool overview page. 

Auth method should be wallet auth.

**Comment by karensheng** [comment]
What Candela pushed should be the transition page (overview page) for investors. The landing page should be the one that shows value prop for investors. 

On the lending pool overview page, Remove the gradient blue background in the three tiles. It makes it hard to read the text. 

<img width="714" alt="Screenshot 2023-12-07 at 3 51 09 PM" src="https://github.com/JurisFund/JurisFund-monorepo/assets/46656667/d0f41838-f26f-4618-996a-4a0f2275c090">

**Comment by Markkos89** [comment]
> What Candela pushed should be the transition page (overview page) for investors. The landing page should be the one that shows value prop for investors.
> 
> On the lending pool overview page, Remove the gradient blue background in the three tiles. It makes it hard to read the text.
> 
> <img alt="Screenshot 2023-12-07 at 3 51 09 PM" width="714" src="https://private-user-images.githubusercontent.com/46656667/288922413-d0f41838-f26f-4618-996a-4a0f2275c090.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5OTM2NDQsIm5iZiI6MTcwMTk5MzM0NCwicGF0aCI6Ii80NjY1NjY2Ny8yODg5MjI0MTMtZDBmNDE4MzgtZjI2Zi00NjE4LTk5NmEtNGEwZjIyNzVjMDkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDIzNTU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhYjNkOTI3YWFlY2EzODQyMDQ2ZjRmYzYwNmU0NzhhZWUyYWZkNzgwOTMyMTg4YWEyYWZhM2JjZjQxZDY2MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TiHj4cQP4Pt4uSp2J2-GEfk6baZ_8FmKPOYOyzmRySg">

changed it on https://github.com/JurisFund/JurisFund-monorepo/pull/54
